from tkinter import *
window=Tk()
window.title("App")
window.iconbitmap('2.jpg')
window.geometry("500x500")
window.resizable(False,False)
window.attributes("-alpha",1)
window.attributes("-topmost",True)
lbl=Label(window,text="Hello",font=('Magneto',15,'bold'))
lbl.pack()
window.mainloop()